services:
    web:
        container_name: e-flow
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        # volumes:
        #     - ./src/TesteTecnico.API/DataBase:/app/DataBase
        environment:
            - ASPNETCORE_ENVIRONMENT=Development